### ISSUE TITLE
INVALID_HEADERS when calling exchangePublicToken or other endpoints

### ISSUE THREAD

**Issue by iwasrobbed** [plaid/plaid-node#245]
Hi there 👋 

Versions: `plaid@^4.5.0` , `node v12.14.1`, [`hapi.js 19.0.5`](https://github.com/hapijs/hapi)

I'm using `LinkKit` on iOS to get a public token and then sending that to the server via [Postman](https://www.postman.com) for now as JSON:

```json
{
	"public_token": "public-development-310.......f381"
}
```

A dump of the request shows:

```shell
headers: {
    'content-type': 'application/json',
...
```

When I call into the server to exchange that for an access token or calling into other APIs like `getTransactions`, Plaid throws an `INVALID_HEADERS` error even though I don't control those headers (to my knowledge).

Here is the client setup code:

```js
const plaidClient = new Plaid.Client(
  process.env.PLAID_CLIENT_ID,
  process.env.PLAID_SECRET,
  process.env.PLAID_PUBLIC_KEY,
  Plaid.environments[process.env.PLAID_ENV],
  { version: '0.1.0',
    webhook: 'https://blah.ngrok.io',
    clientApp: 'MyApp' }
);
```

where the env variables look like:

```
PLAID_CLIENT_ID='some_id_here'
PLAID_SECRET='some_secret_here'
PLAID_PUBLIC_KEY='some_public_key_here'
PLAID_ENV='development'
PLAID_PRODUCTS=auth,transactions
```

and the API call:

```js
static async exchangeForAccessToken(request, h) {
    const publicToken = request.payload.public_token;
    if (!publicToken) { throw Boom.badRequest(); }

    const tokenResponse = await plaidClient.exchangePublicToken(publicToken);
    const accessToken = tokenResponse.access_token;
    const itemId = tokenResponse.item_id;
    return {[PlaidReponseKeys.accessToken]: accessToken, [PlaidReponseKeys.itemId]: itemId};
}
``` 

Stack trace:

```
"stacktrace": [
    "PlaidError: INVALID_HEADERS",
    "at handleApiResponse (/Users/rob/myapp/node_modules/plaid/lib/plaidRequest.js:47:19)",
    "at Request._callback (/Users/rob/myapp/node_modules/plaid/lib/plaidRequest.js:91:7)",
    "at Request.self.callback (/Users/rob/myapp/node_modules/request/request.js:185:22)",
    "at Request.emit (events.js:223:5)",
    "at Request.<anonymous> (/Users/rob/myapp/node_modules/request/request.js:1161:10)",
    "at Request.emit (events.js:223:5)",
    "at IncomingMessage.<anonymous> (/Users/rob/myapp/node_modules/request/request.js:1083:12)",
    "at Object.onceWrapper (events.js:312:28)",
    "at IncomingMessage.emit (events.js:228:7)",
    "at endReadableNT (_stream_readable.js:1185:12)",
    "at processTicksAndRejections (internal/process/task_queues.js:81:21)"
]
```

When I dump the response, it gives a bit more detail:

>res is {"statusCode":400,"body":{"display_message":null,"error_code":"INVALID_HEADERS","error_message":"invalid api version override provided","error_type":"INVALID_REQUEST","request_id":"3a9gILgMjT1MyTU","suggested_action":null},"headers":{"server":"nginx","date":"Tue, 11 Feb 2020 01:04:38 GMT","content-type":"application/json; charset=utf-8","content-length":"222","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"development.plaid.com","port":443,"hostname":"development.plaid.com","hash":null,"search":null,"query":null,"pathname":"/item/public_token/exchange","path":"/item/public_token/exchange","href":"https://development.plaid.com/item/public_token/exchange"},"method":"POST","headers":{"User-Agent":"Plaid Node v4.5.0","Plaid-Version":"0.1.0","Plaid-Client-App":"MyApp","accept":"application/json","content-type":"application/json","content-length":155}}}

The equivalent cURL request works just fine:

```
curl --location --request POST 'https://development.plaid.com/item/public_token/exchange' \
--header 'Content-Type: application/json' \
--data-raw '{
	"client_id": "client_id_here",
	"secret": "client_secret_here",
	"public_token": "public-development-d942.....b418"
}'
```

Am I doing something wrong in the setup or API call? (Seems to match the example). Thanks for any insights!

**Comment by iwasrobbed** [comment]
To follow up, this was caused by me mistakenly passing in `version: '0.1.0'` to the client options upon instantiation and apparently that attempts to override the client version. The docs were very vague about what could go wrong for `INVALID_HEADERS` and the error didn't return much, but dumping the response gave more detail.
